/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class CheeseAnalyzer {
    public static void main(String[] args) {
        CheeseReader reader = new CheeseReader();
        CheeseList cheeses = reader.read("cheese_data.csv");

        int pasteurizedCount =
                cheeses.countByMilkTreatment("Pasteurized");

        int rawMilkCount =
                cheeses.countByMilkTreatment("Raw Milk");

        int organicMoistureCount =
                cheeses.countOrganicAboveMoisture(41.0);

        String mostCommonMilkType =
                cheeses.getMostCommonMilkType();

        CheeseWriter writer = new CheeseWriter();

        writer.write(
                "output.txt",
                pasteurizedCount,
                rawMilkCount,
                organicMoistureCount,
                mostCommonMilkType
        );
    }
}