/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CheeseAnalyzerTest {
    @Test void appHasAGreeting() {
        CheeseAnalyzer classUnderTest = new CheeseAnalyzer();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
